sudo: required
language: java
services:
  - docker
install: true
script:
  - docker build --tag=sdkman/sdkman-cli .
  - docker run --rm -v $PWD:/usr/src/app -v $HOME/.gradle:/root/.gradle sdkman/sdkman-cli clean test --info
after_success:
  - bin/dopublish nyc3.digitaloceanspaces.com sdkman "dist/sdkman-cli-$TRAVIS_BRANCH+$TRAVIS_BUILD_NUMBER.zip" "build/distributions/sdkman-cli-$TRAVIS_BRANCH+$TRAVIS_BUILD_NUMBER.zip"
  - bin/release-binary.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER $MONGO_URL $MONGO_USERNAME $MONGO_PASSWORD
before_cache:
  - sudo rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
