name: Beta Release
on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: "Beta Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew clean test --info
      - name: Set short git hash
        id: var
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build artifacts
        run: ./gradlew -Penv=production -Phash=${{ steps.var.outputs.sha_short }} clean assemble
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Beta release"
          files: |
            build/distributions/sdkman-cli-*.zip