name: Release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./gradlew clean test --info
    - name: Set github tag
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build artifacts
      run: ./gradlew -Penv=production -Prelease=${{ steps.var.outputs.tag }} clean assemble
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/distributions/sdkman-cli-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
